### ISSUE TITLE
Which one do you feel is efficient?

### ISSUE THREAD

**Issue by jcopps** [shashankdeshpande/llm-examples#1]
Noticed that you have tried function calling both the openAI way and langchain way. 
Which one do you think is simpler in terms of maintaining, scalability, accuracy.

**Comment by shashankdeshpande** [comment]
@jcopps That depends on your use case.

Langchain serves as a convenient wrapper around OpenAI, simplifying the overall functionality by parsing OpenAI output and executing function calls. This can be particularly helpful for an initial start.

On the other hand, if you require full control of the workflow and the ability to make customizations, especially with the recent release of parallel function calling by OpenAI, sticking with OpenAI directly might be a better choice.

**Comment by jcopps** [comment]
Cool. Yet to explore the parallel function calling. 
Found the langchain way simpler and more orchestrated. 
Thanks. Closing it.
